version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sweetalert2
    versions:
    - 10.14.0
    - 10.14.1
    - 10.15.0
    - 10.15.1
    - 10.15.2
    - 10.15.4
    - 10.15.5
    - 10.15.6
    - 10.15.7
    - 10.16.0
    - 10.16.2
    - 10.16.3
    - 10.16.4
    - 10.16.5
  - dependency-name: rollup
    versions:
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: stylelint-config-standard
    versions:
    - 21.0.0
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: np
    versions:
    - 7.2.0
    - 7.3.0
    - 7.4.0
  - dependency-name: rollup-plugin-filesize
    versions:
    - 9.1.0
  - dependency-name: rollup-plugin-postcss
    versions:
    - 3.1.8
